// <auto-generated />
using System;
using GestionDeIniciativas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeIniciativas.Migrations
{
    [DbContext(typeof(ListaIniciativasContext))]
    [Migration("20240604063016_IntAño")]
    partial class IntAño
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDeIniciativas.Models.BloqueTiempo", b =>
                {
                    b.Property<string>("TiempoId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Tiempo_ID");

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<string>("DiaMes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Dia_mes");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Dia_semana");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Progreso")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("TareaId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Tarea_ID");

                    b.HasKey("TiempoId")
                        .HasName("PK__BloqueTi__1491EB9DFD9B2020");

                    b.HasIndex("TareaId");

                    b.ToTable("BloqueTiempo", (string)null);
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Iniciativa", b =>
                {
                    b.Property<string>("IniciativaId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Iniciativa_ID");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Usuario_ID");

                    b.HasKey("IniciativaId")
                        .HasName("PK__Iniciati__01A04AEBC244807A");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Iniciativa", (string)null);
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Tarea", b =>
                {
                    b.Property<string>("TareaId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Tarea_ID");

                    b.Property<string>("Categoría")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Horas")
                        .HasColumnType("int");

                    b.Property<int?>("HorasRestantes")
                        .HasColumnType("int");

                    b.Property<string>("IniciativaId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Iniciativa_ID");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Progreso")
                        .HasColumnType("int");

                    b.HasKey("TareaId")
                        .HasName("PK__Tarea__327AB98AF754AB4B");

                    b.HasIndex("IniciativaId");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Usuario_ID");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuario__7711133570AB1D23");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.BloqueTiempo", b =>
                {
                    b.HasOne("GestionDeIniciativas.Models.Tarea", "Tarea")
                        .WithMany("BloqueTiempos")
                        .HasForeignKey("TareaId")
                        .HasConstraintName("fk_tarea");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Iniciativa", b =>
                {
                    b.HasOne("GestionDeIniciativas.Models.Usuario", "Usuario")
                        .WithMany("Iniciativas")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Tarea", b =>
                {
                    b.HasOne("GestionDeIniciativas.Models.Iniciativa", "Iniciativa")
                        .WithMany("Tareas")
                        .HasForeignKey("IniciativaId")
                        .HasConstraintName("fk_iniciativa");

                    b.Navigation("Iniciativa");
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Iniciativa", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Tarea", b =>
                {
                    b.Navigation("BloqueTiempos");
                });

            modelBuilder.Entity("GestionDeIniciativas.Models.Usuario", b =>
                {
                    b.Navigation("Iniciativas");
                });
#pragma warning restore 612, 618
        }
    }
}
